# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: Apache-2.0
#

# Configuration that is needed for MRAM driver as it depends on NRFS which needs
# MULTITHREADING
CONFIG_MULTITHREADING=y
